BaseUrl= "http://syui.github.io/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Hugo Theme Air"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/user.jpg"
  author = "syui"
  authorlocation = ""
  authorwebsite = "http://syui.github.io/hugo-theme-air"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
